import type {
  ScrollScrubScene,
  ScrollScrubTheme,
} from "@/components/scroll-scrub/scroll-scrub";

/** Brand tokens — stark monochrome */
export const scrollScrubTheme: ScrollScrubTheme = {
  accent: "#d4d4d4",
  background: "#080808",
  ink: "#f0f0f0",
  muted: "#666666",
};

export const scrollScrubScenes: ScrollScrubScene[] = [
  {
    id: "scene-01",
    label: "Origin",
    poster: "/assets/world/scene-01-poster.png",
    mobilePoster: "/assets/world/scene-01-poster.png",
    clip: "/assets/world/scene-01.mp4",
    mobileClip: "/assets/world/scene-01-mobile.mp4",
    kicker: "Intelligence",
    title: "Begins in the dark.",
    body: "Every breakthrough starts as a signal in noise. Octo finds what others miss.",
    tags: ["Pattern Recognition", "Signal Extraction"],
    scroll: 1.4,
  },
  {
    id: "scene-02",
    label: "Expand",
    poster: "/assets/world/scene-01-poster.png",
    mobilePoster: "/assets/world/scene-01-poster.png",
    clip: "/assets/world/scene-01.mp4",
    mobileClip: "/assets/world/scene-01-mobile.mp4",
    kicker: "Scale",
    title: "Patterns emerge from noise.",
    body: "Octo processes millions of signals simultaneously, finding structure in chaos.",
    tags: ["Neural Processing", "Real-time"],
    scroll: 1.4,
  },
  {
    id: "scene-03",
    label: "Connect",
    poster: "/assets/world/scene-01-poster.png",
    mobilePoster: "/assets/world/scene-01-poster.png",
    clip: "/assets/world/scene-01.mp4",
    mobileClip: "/assets/world/scene-01-mobile.mp4",
    kicker: "Network",
    title: "Connects the dots.",
    body: "Every data point becomes a node. Octo maps the relationships that matter.",
    tags: ["Graph Architecture", "Contextual Links"],
    scroll: 1.4,
  },
  {
    id: "scene-04",
    label: "Clarify",
    poster: "/assets/world/scene-01-poster.png",
    mobilePoster: "/assets/world/scene-01-poster.png",
    clip: "/assets/world/scene-01.mp4",
    mobileClip: "/assets/world/scene-01-mobile.mp4",
    kicker: "Precision",
    title: "From complexity, clarity.",
    body: "Dense signals reduce to sharp decisions. Octo distills the signal from the noise.",
    tags: ["Decision Engine", "Low Latency"],
    scroll: 1.4,
  },
  {
    id: "scene-05",
    label: "Future",
    poster: "/assets/world/scene-01-poster.png",
    mobilePoster: "/assets/world/scene-01-poster.png",
    clip: "/assets/world/scene-01.mp4",
    mobileClip: "/assets/world/scene-01-mobile.mp4",
    kicker: "Next",
    title: "The future is already here.",
    body: "Octo is built for the problems of tomorrow. Request early access.",
    tags: ["Early Access", "Enterprise"],
    scroll: 1.4,
  },
];
